# Generated by Django 5.2.5 on 2025-09-03 10:44

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'get_latest_by': 'date_opened', 'ordering': [django.db.models.functions.text.Lower('name'), 'date_opened']},
        ),
    ]
